---
abstract: 'Testing session in Mojolicious applications'
author:
  - 'Andrey Khozov <avkhozov@googlemail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mojo-Session
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 3.47
resources:
  bugtracker: https://github.com/avkhozov/test-mojo-session/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avkhozov/test-mojo-session
version: 1.0
